### ISSUE TITLE
SDT binary file

### ISSUE THREAD

**Issue by pratikshaya** [B05901022/Note-Segmentation-SSL#1]
Each wave file in the dataset has its corresponding binary sdt file. All the sdt file for training and testing dataset has given. But, can you please tell me how to generate this sdt file from the dataset?

**Comment by B05901022** [comment]
The sdt files are generated by the following steps:
1. Directly map duration/onset/offset from ground truth to its corresponding frame.
2. Applying a smoothing process that labels the neighboring 2 frames as the same tag. Thus, including the original frame, a total of 5 frames (excluding frames on the boundaries) are tagged as the same duration/onset/offset label. Labels are cropped by the original number of frames.

Taking DALI for example,
```python
import scipy.io.wavfile as wavfile
import numpy as np
import DALI as dali_code
import os
import math
from typing import Dict

def read_entry(filename: str, dali_dict: str):
    return dali_dict[filename]

def get_sdt(filename: str, dali_dict: Dict) -> np.ndarray:
    entry = read_entry(filename, dali_dict)
    audio, sample_rate = wavfile.read(os.path.join(AUDIO_WAV_FOLDER, filename))
    sdt_length = math.ceil(audio.shape[-1]/sample_rate/0.02)-1 # we use 0.02 sec frame width
    sdt = np.zeros((sdt_length, 6))
    for single_note in entry.annotations['annot']['notes']:
        onset, offset = single_note['time']
        onset = round(onset*50) # 0.02 sec frame width
        offset = round(offset*50) # 0.02 sec frame width
        try:
            # solve mismatch issues
            sdt[max(onset,    0):min(offset+2, sdt_length)-1, 1] = 1 # Duration
            sdt[max(onset-2,  0):min(onset+4,  sdt_length)-1, 3] = 1 # Onset
            sdt[max(offset-2, 0):min(offset+4, sdt_length)-1, 5] = 1 # Offset
        except:
            pass
    sdt[:,0] = np.logical_not(sdt[:,1])
    sdt[:,2] = np.logical_not(sdt[:,3])
    sdt[:,4] = np.logical_not(sdt[:,5])
    return sdt.astype(np.int) # to minimize the file size
    
if __name__ == "__main__":

    # directories
    DALI_GT_FILES = "path/to/DALI_v1.0/"
    AUDIO_WAV_FOLDER = "folder/that/contains/wav/files/"
    META_TXT_FILE = "./meta/dali_demucs_valid.txt"
    SAVE_DIRECTORY = "path/to/save/sdt/files/"
    
    # load dali ground truth and meta file
    FILE_LIST = open(META_TXT_FILE).read().split()
    DALI_LIST = dali_code.get_the_DALI_dataset(os.path.abspath(DALI_GT_FILES))
    DALI_FILE_DICT = {i: DALI_LIST[i] for i in FILE_LIST}
    
    for filename in FILE_LIST:
        sdt_file = get_sdt(filename, DALI_FILE_DICT)
        np.save(os.path.join(SAVE_DIRECTORY, filename+"_sdt"), sdt_file)
```
Some modifications need to be done between different datasets. Also ensure that the generated sdt files have the same length as the generated features. Hope this can help you out!

**Comment by pratikshaya** [comment]
Thank you for your nice reply

**Comment by ivylijingru** [comment]
@B05901022  I used the script in this issue for TONAS dataset, while it turns out that the result is different from the sdt files you provided (about 5% error rate). So how to reproduce the sdt you provided for TONAS dataset? Thanks.

**Comment by B05901022** [comment]
@ivylijingru Thank you for your comment! After a short discussion with the author which I adapted dataset and [code](https://github.com/Itachi6912110/Hierarchical-Note-Segmentation) from. He believed that the sdt data was directly downloaded from a source that is hard to recall, and unfortunately his backup files were corrupted. But since the only source I could found on the internet now is the metadata together with the dataset, I believe the result by the above code will be more reliable.

**Comment by ivylijingru** [comment]
Thanks for your response! I'll use the above code instead.
