### ISSUE TITLE
Generate sdt files

### ISSUE THREAD

**Issue by WeiShi78** [B05901022/Note-Segmentation-SSL#9]
Hi,

I wonder do you have the scripts to generate sdt.npy files? I would like to try with my own training datasets and my own scripts to generate sdt files doesn't work appropriately for the model input.

Thanks!

**Comment by B05901022** [comment]
Hi,

Please refer to [this issue](https://github.com/B05901022/Note-Segmentation-SSL/issues/1).

**Comment by WeiShi78** [comment]
Thanks!
